<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Identity\Views\Home\NewFolder\**" />
    <Compile Remove="Areas\Property\Views\Home\NewFolder\**" />
    <Content Remove="Areas\Identity\Views\Home\NewFolder\**" />
    <Content Remove="Areas\Property\Views\Home\NewFolder\**" />
    <EmbeddedResource Remove="Areas\Identity\Views\Home\NewFolder\**" />
    <EmbeddedResource Remove="Areas\Property\Views\Home\NewFolder\**" />
    <None Remove="Areas\Identity\Views\Home\NewFolder\**" />
    <None Remove="Areas\Property\Views\Home\NewFolder\**" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.10.3" />
		<PackageReference Include="Mapster" Version="7.4.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
		</PackageReference>
	</ItemGroup>

</Project>
